!!python/object:vhap.config.base.BaseTrackingConfig
async_func: true
begin_frame_idx: 0
begin_stage: null
data: !!python/object:vhap.config.base.DataConfig
  _target: vhap.data.video_dataset.VideoDataset
  align_cameras_to_axes: true
  background_color: white
  calibrated: false
  camera_convention_conversion: opencv->opengl
  division: null
  landmark_source: star
  n_downsample_rgb: null
  root_folder: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - newub
  - w
  - vamp-interface
  - exp_output
  - lam_bakeoff
  - take_runs
  - MySlate_4_full
  - preprocess
  scale_factor: 1.0
  sequence: MySlate_4
  subset: null
  target_extrinsic_type: w2c
  use_alpha_map: false
  use_landmark: true
device: cuda
exp: !!python/object:vhap.config.base.ExperimentConfig
  keyframes: !!python/tuple []
  output_folder: !!python/object/apply:pathlib.PosixPath
  - /
  - home
  - newub
  - w
  - vamp-interface
  - exp_output
  - lam_bakeoff
  - take_runs
  - MySlate_4_full
  - tracking
  photometric: false
  reuse_landmarks: true
log: !!python/object:vhap.config.base.LogConfig
  image_format: jpg
  interval_media: 500
  interval_scalar: 100
  max_num_views: 3
  stack_views_in_rows: true
  view_indices: !!python/tuple []
lr: !!python/object:vhap.config.base.LearningRateConfig
  base: 0.005
  camera: 0.005
  dynamic_offset: 0.0005
  expr: 0.05
  light: 0.005
  static_offset: 0.0005
  translation: 0.001
model: !!python/object:vhap.config.base.ModelConfig
  add_teeth: true
  flame_params_path: null
  n_expr: 100
  n_shape: 300
  n_tex: 100
  occluded: !!python/tuple
  - hair
  - hair
  remove_lip_inside: false
  residual_tex: true
  tex_clusters: !!python/tuple
  - skin
  - hair
  - boundary
  - lips_tight
  - teeth
  - sclerae
  - irises
  tex_extra: true
  tex_painted: true
  tex_resolution: 2048
  use_dynamic_offset: false
  use_static_offset: false
pipeline: !!python/object:vhap.config.base.PipelineConfig
  lmk_global_tracking: !!python/object:vhap.config.base.StageLmkGlobalTrackingConfig
    disable_jawline_landmarks: false
    num_epochs: 0
    optimizable_params: &id001 !!python/tuple
    - cam
    - pose
    - shape
    - joints
    - expr
  lmk_init_all: !!python/object:vhap.config.base.StageLmkInitAllConfig
    disable_jawline_landmarks: false
    num_steps: 300
    optimizable_params: *id001
  lmk_init_rigid: !!python/object:vhap.config.base.StageLmkInitRigidConfig
    disable_jawline_landmarks: false
    num_steps: 300
    optimizable_params: !!python/tuple
    - cam
    - pose
  lmk_sequential_tracking: !!python/object:vhap.config.base.StageLmkSequentialTrackingConfig
    disable_jawline_landmarks: false
    num_steps: 50
    optimizable_params: !!python/tuple
    - pose
    - joints
    - expr
  rgb_global_tracking: !!python/object:vhap.config.base.StageRgbGlobalTrackingConfig
    align_boundary_except: !!python/tuple
    - bottomline
    - hair
    - hair
    - hair
    align_texture_except: !!python/tuple
    - hair
    - hair
    - hair
    disable_jawline_landmarks: true
    num_epochs: 30
    optimizable_params: !!python/tuple
    - cam
    - pose
    - shape
    - joints
    - expr
    - texture
    - lights
    - static_offset
    - dynamic_offset
  rgb_init_all: !!python/object:vhap.config.base.StageRgbInitAllConfig
    align_boundary_except: !!python/tuple
    - hair
    - bottomline
    - hair
    - hair
    - hair
    align_texture_except: !!python/tuple
    - hair
    - boundary
    - neck
    - hair
    - hair
    - hair
    disable_jawline_landmarks: true
    num_steps: 500
    optimizable_params: !!python/tuple
    - cam
    - pose
    - shape
    - joints
    - expr
    - texture
    - lights
  rgb_init_offset: !!python/object:vhap.config.base.StageRgbInitOffsetConfig
    align_boundary_except: !!python/tuple
    - bottomline
    - hair
    - hair
    - hair
    align_texture_except: !!python/tuple
    - hair
    - boundary
    - neck
    - hair
    - hair
    - hair
    disable_jawline_landmarks: true
    num_steps: 500
    optimizable_params: !!python/tuple
    - cam
    - pose
    - shape
    - joints
    - expr
    - texture
    - lights
    - static_offset
  rgb_init_texture: !!python/object:vhap.config.base.StageRgbInitTextureConfig
    align_boundary_except: !!python/tuple
    - hair
    - boundary
    - hair
    - hair
    - hair
    align_texture_except: !!python/tuple
    - hair
    - boundary
    - neck
    - hair
    - hair
    - hair
    disable_jawline_landmarks: false
    num_steps: 500
    optimizable_params: !!python/tuple
    - cam
    - shape
    - texture
    - lights
  rgb_sequential_tracking: !!python/object:vhap.config.base.StageRgbSequentialTrackingConfig
    align_boundary_except: !!python/tuple
    - bottomline
    - hair
    - hair
    - hair
    align_texture_except: !!python/tuple
    - hair
    - hair
    - hair
    disable_jawline_landmarks: true
    num_steps: 50
    optimizable_params: !!python/tuple
    - pose
    - joints
    - expr
    - texture
    - dynamic_offset
render: !!python/object:vhap.config.base.RenderConfig
  backend: nvdiffrast
  background_eval: target
  background_train: target
  disturb_rate_bg: 0.5
  disturb_rate_fg: 0.5
  lighting_space: world
  lighting_type: SH
  use_opengl: false
w: !!python/object:vhap.config.base.LossWeightConfig
  always_enable_jawline_landmarks: true
  blur_iter: 0
  landmark: 10.0
  photo: 30.0
  prior_eyes: 0.03
  prior_jaw: 0.3
  prior_neck: 0.3
  reg_diffuse: 100.0
  reg_expr: 0.03
  reg_light: null
  reg_offset: 300.0
  reg_offset_dynamic: 300000.0
  reg_offset_lap: 1000000.0
  reg_offset_lap_relax_coef: 0.1
  reg_offset_lap_relax_for: &id002 !!python/tuple
  - hair
  - ears
  reg_offset_relax_coef: 1.0
  reg_offset_relax_for: *id002
  reg_offset_rigid: 300.0
  reg_offset_rigid_for: !!python/tuple
  - left_ear
  - right_ear
  - neck
  - left_eye
  - right_eye
  - lips_tight
  reg_shape: 0.3
  reg_tex_pca: 0.0001
  reg_tex_res: null
  reg_tex_res_clusters: 10.0
  reg_tex_res_for: !!python/tuple
  - sclerae
  - teeth
  reg_tex_tv: 10000.0
  smooth_eyes: 0
  smooth_jaw: 0.1
  smooth_neck: 30.0
  smooth_rot: 30.0
  smooth_trans: 300.0
